# Generated by Django 2.2 on 2020-07-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='giturl',
            field=models.TextField(default='/'),
        ),
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.TextField(default='/'),
        ),
    ]
